inherit_mode:
  merge:
    - Exclude
    - Include
AllCops:
  TargetRubyVersion: 2.6
  NewCops: enable
  Exclude:
    - '**/db/**/*'
    - '**/app/views/*'
    - '**/config/**'
    - '**/script/**'
    - '/spec/**'
    - '**.haml'
Bundler/OrderedGems:
  Enabled: false
Style/EmptyCaseCondition:
  Enabled: false
Style/HashEachMethods:
  Enabled: true
Style/HashTransformKeys:
  Enabled: true
Style/HashTransformValues:
  Enabled: true
Style/RedundantPercentQ:
  Enabled: false
Layout/DotPosition:
  Enabled: false
Layout/EmptyLines:
  Enabled: false
Layout/EmptyLinesAroundClassBody:
  Enabled: false
Layout/EmptyLinesAroundModuleBody:
  Enabled: false
Layout/HashAlignment:
  Enabled: false
Layout/LineLength:
  Enabled: false
Layout/MultilineMethodCallIndentation:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/BlockLength:
  Enabled: true
  Exclude:
    - 'config/routes.rb'
    - 'config/routes/*'
    - 'Gemfile'
    - '**/db/**/*'
    - '**/test/**/*'
    - '**/spec/**/*'
Metrics/ClassLength:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Naming/PredicateName:
  Enabled: false
Naming/MethodParameterName:
  AllowedNames:
    cc
Style/Documentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/HashSyntax:
  Enabled: false
Style/NumericLiterals:
  Enabled: true
  Exclude:
    - '**/test/**/*'
    - '**/spec/**/*'
Style/CommentedKeyword:
  Enabled: false
Style/SymbolArray:
  Enabled: false
Style/TernaryParentheses:
  Enabled: true
  EnforcedStyle: 'require_parentheses_when_complex'
Style/TrailingCommaInArguments:
  Enabled: false
Style/TrailingCommaInHashLiteral:
  Enabled: false
Style/TrailingCommaInArrayLiteral:
  Enabled: false
Style/TrailingUnderscoreVariable:
  Enabled: false
Style/TrivialAccessors:
  Enabled: false
  IgnoreClassMethods: true
